# This file contains values from Cookiecutter

default_context:
  project_name: "rdf-linkchecker"
  project_description: "Awesome `rdf-linkchecker` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "WWU-AMM"
  license: "BSD-3"
  minimal_python_version: 3.7
  github_name: "renefritze"
  email: "rene.fritze@wwu.de"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
